export const UPDATE_AUTH_INFO = "UPDATE_AUTH_INFO";
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_REQUEST_SUCCESS = "REGISTER_USER_REQUEST_SUCCESS";
export const REGISTER_USER_REQUEST_ERROR = "REGISTER_USER_REQUEST_ERROR";
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_REQUEST_SUCCESS = "LOGIN_USER_REQUEST_SUCCESS";
export const LOGIN_USER_REQUEST_ERROR = "LOGIN_USER_REQUEST_ERROR";
export const SIGN_OUT = "SIGN_OUT";
